name: kelebikev2
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  cupertino_icons: ^1.0.2
  dart_json_mapper: ^2.2.7
  auto_route: ^5.0.4
  hive: ^2.2.3
  permission_handler: ^10.2.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  flutter_phoenix: ^1.1.0
  fluttertoast: ^8.1.1
  adaptive_dialog: ^1.8.0+1
  provider: ^6.0.4
  animate_do: ^3.0.2
  google_fonts: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  
  build_runner:
  auto_route_generator:
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon.png"
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - languages/
    - assets/logos/

  uses-material-design: true


